### ISSUE TITLE
Adding Buy and sell signal to backtest graph

### ISSUE THREAD

**Issue by ben1628** [Heerozh/spectre#11]
Using your backtest script, how can one add Close Price, Buy and Sell signal to the chart so we can see them visually...

Currently, it shows Portfolio benchmark and turnover.

I'm new to Python so may not understand everything about it.

**Comment by Heerozh** [comment]
You need to plot yourself. 

The results returned by the backtest contain all the data, use them.

Similar sample code can be found in zipline lib, and I recommend using zipline lib directly for such needs.

**Comment by ben1628** [comment]
Great project. Thanks
