### ISSUE TITLE
how to calculate rolling factors

### ISSUE THREAD

**Issue by sherryhooo** [Heerozh/spectre#13]
hi, heerozh, I am not not familiar with PyTorch, could you help me with calculating factors like Average close prices over 4-weeks divided by average close prices over 52-weeks? Do I need define a new function in your spectre.parallel.Rolling class? Thanks a lot

**Comment by Heerozh** [comment]
> hi, heerozh, I am not not familiar with PyTorch, could you help me with calculating factors like Average close prices over 4-weeks divided by average close prices over 52-weeks? Do I need define a new function in your spectre.parallel.Rolling class? Thanks a lot

```engine.add(factors.MA(20) / factors.MA(260), 'name')```
