### ISSUE TITLE
请问如何用于中国A股？

### ISSUE THREAD

**Issue by quant2008** [Heerozh/spectre#17]
请问如何用于中国A股？谢谢

**Comment by Heerozh** [comment]
怎么突然今天好几个人来问，你们是哪里来的？

这个库是和啥市场无关的，数据需要自己解决

**Comment by quant2008** [comment]
我是量化爱好者哈，你这个和微软的qlib框架性能比较过吗，哪个速度更快？

**Comment by Heerozh** [comment]
目标不一样，单说计算效率的话快50倍-100倍

**Comment by quant2008** [comment]
有几个问题请教：
1 您这个是不是没有限价单。限价单功能很重要。
2 一字涨跌停不能买卖问题解决了吗？
3 在某bar的开始下单，成交是该bar的开盘价，还是收盘价，还是下一个bar的开盘价或收盘价？

**Comment by Heerozh** [comment]
你说的功能虽然都有，但spectre主要不是回测用的。是面向机构的，并不关注你这些问题，爱好者建议还是用市面上的其他软件

**Comment by quant2008** [comment]
我同意，您这个主要是因子计算，因子计算速度一流，远超zipline pipeline。
但如果回测功能也全面而快速的话，岂不是更好。可以理解回测部分的速度和zipline是一个量级的吗？
