### ISSUE TITLE
请问您的回测程序功能是不是和zipline一样的

### ISSUE THREAD

**Issue by qtbgo** [Heerozh/spectre#19]
感谢发布这个非常棒的程序。请问回测程序是不是功能和zipline一样。zipline不能用于a股，您这个可以。

**Comment by Heerozh** [comment]
zipline也可以用在a股，我这个也一样，主要按美股设计的

**Comment by qtbgo** [comment]
zipline要改一些东西吧用于a股。你这个看起来是CSV直接用。不知回测性能比zipline咋样

**Comment by quant2008** [comment]
请问您的回测程序是否包含了zipline所有的回测功能（绘图不要求）？
