### ISSUE TITLE
is it possible to set universe updated every 30 days?

### ISSUE THREAD

**Issue by temph2020** [Heerozh/spectre#28]
In spectre, We can define universe as: universe = factors.AverageDollarVolume(win=21).top(1000)
This universe is updated everyday.

I wonder if it is possible to update it, for example, every 30 days instead?

This way, when backtesting, in the rebalance function, I can  compute covariance matrix every 30 days.

**Comment by Heerozh** [comment]
involves basic knowledge, I don’t have time to answer it right now, suggest you read some relevant books
close
