### ISSUE TITLE
GPU accellerated Backtest

### ISSUE THREAD

**Issue by MarkusEvo** [Heerozh/spectre#8]
Hey,
I was wondering if there was a way to compute portfolio returns / sharpe ratio or drawdowns etc. as factors or GPU accellerated in general. I'm working on a project were I have to do alot of backtests and was wondering if that was possible.

**Comment by Heerozh** [comment]
Unfortunately gpu accelerated backtest is impossible, you need to find other ways

**Comment by MarkusEvo** [comment]
okidoki
